### PR TITLE
fix(config): add support for absolute outputDir and sourcefile

### LINKED ISSUE #3: breaks if sourcefile is absolute
if sourcefile is absolute, I get: 

`Warning: ENOENT, no such file or directory`

you can clearly see it in the code:

image

### PR DESCRIPTION
**Pull request by guy-mograbi-at-gigaspaces**
fixes #3

### CODE REVIEW

**Comment by linslin** [comment]
Hey @guy-mograbi-at-gigaspaces, could you push this changes into develop branch? I drive gitflow. Thanks!

**Comment by guy-mograbi-at-gigaspaces** [comment]
develop on my fork?
or a fix branch on my fork?

**Comment by linslin** [comment]
Just push the changes into this branch: https://github.com/linslin/grunt-jscpd-reporter/tree/develop instead of master.

**Comment by guy-mograbi-at-gigaspaces** [comment]
Not sure I understand. I don't think I have permissions to do so and I don't understand how that has anything to do with gitflow.

**Comment by linslin** [comment]
Simple explained: Gitflow assumes features to be merged with a develop branch before mergin into master. In that way I can check if develop is still stable and merge your changes with other features. The hole tested bundle will be released as a nice and almost stable version into master branch. 

Please check this link: https://help.github.com/articles/using-pull-requests/#changing-the-branch-range-and-destination-repository. 

or via CLI: 

`git merge https://github.com/linslin/grunt-jscpd-reporter/tree/develop` to create a pull request to develop branch.

**Comment by guy-mograbi-at-gigaspaces** [comment]
oh! change the destination branch... now I see. doing it..

**Comment by guy-mograbi-at-gigaspaces** [comment]
seems like I need to close this PR and open another
https://github.com/isaacs/github/issues/18

**Comment by guy-mograbi-at-gigaspaces** [comment]
see https://github.com/linslin/grunt-jscpd-reporter/pull/5

**Pull request closed without merging**
